### PR TITLE
Handle file descriptor ownership and update documents for GDS

### LINKED ISSUE #233: [BUG] The file descriptor for cuFile (GDS) is not closed after use
**Describe the bug**

If a CuFileDriver instance is created by the file descriptor (fd), the file descriptor needs to be closed manually.
However, if the CuFileDriver instance is created by cucim.clara.filesystem.open() method, its file descriptor needs to be closed automatically when the reference count is zero.

**Steps/Code to reproduce bug**

```python
from cucim.clara.filesystem import CuFileDriver
import cucim.clara.filesystem as fs
import os, cupy as cp, torch

# Create a CuPy array with size 10 (in bytes)
cp_arr = cp.ones(10, dtype=cp.uint8)
# Create a PyTorch array with size 10 (in bytes)
cuda0 = torch.device('cuda:0')
torch_arr = torch.ones(10, dtype=torch.uint8, device=cuda0)

# Using CuFileDriver
# (Opening a file with O_DIRECT flag is required for GDS)
fno = os.open("input.raw", os.O_RDONLY | os.O_DIRECT)
with CuFileDriver(fno) as fd:
  # Read 8 bytes starting from file offset 0 into buffer offset 2
  read_count = fd.pread(cp_arr, 8, 0, 2)
  # Read 10 bytes starting from file offset 3
  read_count = fd.pread(torch_arr, 10, 3)
os.close(fno)

# Another way of opening file with cuFile
with fs.open("output.raw", "w") as fd:
  # Write 10 bytes from cp_array to file starting from offset 5
  write_count = fd.pwrite(cp_arr, 10, 5)
  #############################################
  # <=== file descriptor created by fs.open() is not closed when exiting the scope
  #############################################
```

**Expected behavior**
It should close the file descriptor.

**Environment details (please complete the following information):**
 - Environment location: Bare-metal
 - Method of cuCIM install: pip, from source

### PR DESCRIPTION
**Pull request by gigony**
- Close the file descriptor if the file descriptor is owned by the object.
- Update GDS example in the Jupyter notebook.

```python
from cucim.clara.filesystem import CuFileDriver
import cucim.clara.filesystem as fs
import os, cupy as cp, torch

# Create a CuPy array with size 10 (in bytes)
cp_arr = cp.ones(10, dtype=cp.uint8)
# Create a PyTorch array with size 10 (in bytes)
cuda0 = torch.device('cuda:0')
torch_arr = torch.ones(10, dtype=torch.uint8, device=cuda0)

# Using CuFileDriver
# (Opening a file with O_DIRECT flag is required for GDS)
fno = os.open("input.raw", os.O_RDONLY | os.O_DIRECT)
with CuFileDriver(fno) as fd:
  # Read 8 bytes starting from file offset 0 into buffer offset 2
  read_count = fd.pread(cp_arr, 8, 0, 2)
  # Read 10 bytes starting from file offset 3
  read_count = fd.pread(torch_arr, 10, 3)
os.close(fno)

# Another way of opening file with cuFile
with fs.open("output.raw", "w") as fd:
  # Write 10 bytes from cp_array to file starting from offset 5
  write_count = fd.pwrite(cp_arr, 10, 5)
  #############################################
  # <=== file descriptor created by fs.open() would be closed when exiting the scope
  #############################################
```

Fixes #233

### CODE REVIEW

File: cpp/include/cucim/filesystem/file_handle.h [hunk 1]
```diff
@@ -70,6 +74,13 @@ struct EXPORT_VISIBLE CuCIMFileHandle : public std::enable_shared_from_this<CuCI
             deleter(this);
             deleter = nullptr;
         }
+
+        if (own_fd)
```
Comment (jakirkham) [inline cpp/include/cucim/filesystem/file_handle.h:78]: Should we check `fd` too? Is there any risk it is undefined?

File: notebooks/Accessing_File_with_GDS.ipynb [hunk 2]
```diff
@@ -253,11 +248,13 @@
     "read_count = fd.pread(torch_arr.data_ptr(), 10, 3)      # read 10 bytes starting from file offset 3\n",
     "print(\"{:10} cnt: {}  content: {}\".format(\"torch_arr\", read_count, torch_arr))\n",
     "fd.close()\n",
+    "os.close(fno)\n",
     "\n",
     "fno = os.open(\"output.raw\", os.O_RDWR | os.O_CREAT | os.O_TRUNC)\n",
     "fd = CuFileDriver(fno)\n",
     "write_count = fd.pwrite(np_arr, 10, 5)      # write 10 bytes from np_array to file starting from offset 5\n",
     "fd.close()\n",
+    "os.close(fno)\n",
```
Comment (jakirkham) [inline notebooks/Accessing_File_with_GDS.ipynb:257]: Might be worth writing this to use [a context manager (`with` statement)]( https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files ). Just a thought 🙂

**Comment by jakirkham** [comment]
Thanks Gigon! 😄 Generally looks good. Had a couple questions above 🙂

File: cpp/include/cucim/filesystem/file_handle.h (hunk 1 above)
Comment (gigony) [reply cpp/include/cucim/filesystem/file_handle.h:78]: Thanks @jakirkham for the feedback! 
Will update to make sure to check fd (`fd >= 0`).

File: notebooks/Accessing_File_with_GDS.ipynb (hunk 2 above)
Comment (gigony) [reply notebooks/Accessing_File_with_GDS.ipynb:257]: Thanks for the review!

This is to showcase the different ways to call the methods.
Here, I couldn't use with statement for `os.close(fno)` because Python's built-in os.open() returns `int` type and there is no context manager available.

Comment (jakirkham) [reply notebooks/Accessing_File_with_GDS.ipynb:257]: We can always [roll our own]( https://docs.python.org/3/library/contextlib.html#contextlib.contextmanager ). Though maybe that's unnecessary for an example.

Comment (gigony) [reply notebooks/Accessing_File_with_GDS.ipynb:257]: I am not sure if we want to provide such a wrapper in Python for the file descriptor(int).

`with` is supported by our API. the recommended way for using it (without close method) is described in the notebook and a description of the GDS reader page so don't need to change here?

https://github.com/NVIDIA/MagnumIO/tree/main/gds/readers/cucim-gds

```python
with fs.open("output.raw", "w") as fd:
    # Write 10 bytes from cp_array to file starting from offset 5
    write_count = fd.pwrite(cp_arr, 10, 5)
```

**Review by jakirkham — APPROVED** [review]

**Comment by jakirkham** [comment]
@gpucibot merge

**Comment by jakirkham** [comment]
Thanks Gigon! 😄
